name: Build and upload docker image
on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - '**'

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      
      - name: Check if docker available or not
        run : which docker

      - env:
          DOCKER_IMAGE_TAG: $((git log -1 --pretty=format:%h))
      
      - name: build fronend
        run : docker build -t mern-fe:${DOCKER_IMAGE_TAG} ./client
      
      - name: build backend
        run: docker build -t mern-be:${DOCKER_IMAGE_TAG} ./server
 