name: Build and upload docker image
on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - **

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      
      - name: Check if docker available or not
      - run : which docker
 